### PR TITLE
Throw IllegalArgumentException at invalid time zone textual representation instead of defaulting to GMT

### LINKED ISSUE #650: FormattedTimestampJsonProvider#setTimeZone defaults to GMT if the zoneId is not a valid zone id
`FormattedTimestampJsonProvider#setTimeZone(ID)` delegates to `TimeZone.getTimeZone(ID)` to convert the supplied zone id into a valid ZoneId instance. However, as indicated by the javadoc, this method will not fail if the supplied zone id is not a valid zone identifier but returns GMT instead:

```
@return the specified <code>TimeZone</code>, or the GMT zone if the given ID cannot be understood.
```
 
This behaviour is confusing - FormattedTimestampJsonProvider should throw an IllegalArgumentException instead of silently revert to GMT in case of invalid zone id.

### PR DESCRIPTION
**Pull request by brenuart**
Closes #650.

### CODE REVIEW

File: src/main/java/net/logstash/logback/composite/FormattedTimestampJsonProvider.java [hunk 1]
```diff
@@ -204,11 +204,60 @@ public void setPattern(String pattern) {
...
+     *         <i>Digit</i> <i>Digit</i>
+     * <i>Digit:</i> one of
+     *         <code>0 1 2 3 4 5 6 7 8 9</code>
+     * </pre></blockquote>
+     *
+     * <i>Hours</i> must be between 0 to 23 and <i>Minutes</i> must be
+     * between 00 to 59.  For example, "GMT+10" and "GMT+0010" mean ten
+     * hours and ten minutes ahead of GMT, respectively.
+     * 
+     * <p>Use a blank string or {@code null} to use the default TimeZone of the system.
```
Comment (brenuart) [inline src/main/java/net/logstash/logback/composite/FormattedTimestampJsonProvider.java:250]: Joran does not allow to set a blank string nor a null value... May be we need another way here for the user to say it wants the default time zone of the system... ?

File: README.md [hunk 2]
```diff
@@ -1639,7 +1639,36 @@ You can change the timezone like this:
...
+         
+      Minutes:
+         Digit Digit
+
+      Digit: one of
+         0 1 2 3 4 5 6 7 8 9
+```
+
+_Hours_ must be between 0 to 23 and _Minutes_ must be between 00 to 59. 
+For example, "GMT+10" and "GMT+0010" mean ten hours and ten minutes ahead of GMT, respectively.
```
Comment (philsttr) [inline README.md:1669]: I don't think logstash-logback-encoder should document the full format of the time zone string supported by java.util.Timezone, since logstash-logback-encoder is not responsible for parsing the string.   I don't want to have to keep this documentation up to date with the java.util.Timezone implementation/documentation.

I'd like to simplify this to something like...

The value of the `timeZone` element can be any string accepted by java's `TimeZone.getTimeZone(String id)` method. For example `America/Los_Angeles` or `GMT+10`

File: src/main/java/net/logstash/logback/composite/FormattedTimestampJsonProvider.java (hunk 1 above)
Comment (philsttr) [reply src/main/java/net/logstash/logback/composite/FormattedTimestampJsonProvider.java:250]: Adding a special case for "DEFAULT" seems ok to me.

File: src/main/java/net/logstash/logback/util/TimeZoneUtils.java [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+     * <i>Minutes:</i>
+     *         <i>Digit</i> <i>Digit</i>
+     * <i>Digit:</i> one of
+     *         <code>0 1 2 3 4 5 6 7 8 9</code>
+     * </pre></blockquote>
+     *
+     * <i>Hours</i> must be between 0 to 23 and <i>Minutes</i> must be
+     * between 00 to 59.  For example, "GMT+10" and "GMT+0010" mean ten
+     * hours and ten minutes ahead of GMT, respectively.
+     *
```
Comment (philsttr) [inline src/main/java/net/logstash/logback/util/TimeZoneUtils.java:58]: Same comment as readme.  Let's not repeat the TimeZone string documentation here, but just give some examples and point to the TimeZone documentation for exact format.

File: src/main/java/net/logstash/logback/composite/FormattedTimestampJsonProvider.java (hunk 1 above)
Comment (brenuart) [reply src/main/java/net/logstash/logback/composite/FormattedTimestampJsonProvider.java:250]: `[DEFAULT]` can now be used to refer to the system default time zone (between brackets to follow same convention as used by the `pattern` property of the same class).

**Review by philsttr — APPROVED** [review]
